import { mysqlTable, mysqlSchema, AnyMySqlColumn, index, foreignKey, int, decimal, timestamp, text, varchar, mysqlEnum, json, tinyint } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const catchBatches = mysqlTable("catch_batches", {
	id: int().autoincrement().notNull(),
	sessionId: int().notNull().references(() => catchSessions.id),
	crateTypeId: int().notNull().references(() => crateTypes.id),
	batchNumber: int().notNull(),
	numberOfCrates: int().notNull(),
	birdsPerCrate: int().notNull(),
	totalBirds: int().notNull(),
	totalGrossWeight: decimal({ precision: 10, scale: 3 }).notNull(),
	crateWeight: decimal({ precision: 8, scale: 3 }).notNull(),
	palletWeight: decimal({ precision: 8, scale: 3 }),
	totalNetWeight: decimal({ precision: 10, scale: 3 }).notNull(),
	averageBirdWeight: decimal({ precision: 8, scale: 3 }).notNull(),
	recordedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	notes: text(),
},
(table) => [
	index("idx_catch_batches_session_id").on(table.sessionId),
	index("idx_catch_batches_crate_type_id").on(table.crateTypeId),
]);

export const catchConfigurations = mysqlTable("catch_configurations", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	targetDeliveredWeight: decimal({ precision: 10, scale: 3 }).notNull(),
	calculatedCatchingWeight: decimal({ precision: 10, scale: 3 }).notNull(),
	feedWithdrawalLossPercent: decimal({ precision: 5, scale: 2 }).default('4.00').notNull(),
	catchingLoadingLossPercent: decimal({ precision: 5, scale: 2 }).default('0.70').notNull(),
	transportLossPercentPerHour: decimal({ precision: 5, scale: 2 }).default('0.30').notNull(),
	lairageLossPercent: decimal({ precision: 5, scale: 2 }).default('0.20').notNull(),
	transportDurationHours: decimal({ precision: 5, scale: 2 }).default('2.00').notNull(),
	totalShrinkagePercent: decimal({ precision: 5, scale: 2 }).notNull(),
	plannedCatchDates: text(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("flockId").on(table.flockId),
	index("idx_catch_config_flock_id").on(table.flockId),
]);

export const catchCrates = mysqlTable("catch_crates", {
	id: int().autoincrement().notNull(),
	sessionId: int().notNull().references(() => catchSessions.id),
	crateTypeId: int().notNull().references(() => crateTypes.id),
	batchId: varchar({ length: 50 }),
	crateNumber: int().notNull(),
	birdCount: int().notNull(),
	grossWeight: decimal({ precision: 8, scale: 3 }).notNull(),
	netWeight: decimal({ precision: 8, scale: 3 }).notNull(),
	averageBirdWeight: decimal({ precision: 8, scale: 3 }).notNull(),
	recordedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	notes: text(),
},
(table) => [
	index("idx_catch_crates_session_id").on(table.sessionId),
	index("idx_catch_crates_crate_type_id").on(table.crateTypeId),
]);

export const catchSessions = mysqlTable("catch_sessions", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	catchDate: timestamp({ mode: 'string' }).notNull(),
	catchTeam: varchar({ length: 200 }),
	targetBirds: int(),
	targetWeight: decimal({ precision: 10, scale: 3 }),
	status: varchar({ length: 20 }).default('active').notNull(),
	startTime: timestamp({ mode: 'string' }).notNull(),
	endTime: timestamp({ mode: 'string' }),
	totalBirdsCaught: int().default(0).notNull(),
	totalNetWeight: decimal({ precision: 10, scale: 3 }).default('0.000').notNull(),
	totalCrates: int().default(0).notNull(),
	averageBirdWeight: decimal({ precision: 8, scale: 3 }),
	harvestRecordId: int().references(() => harvestRecords.id),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
	weighingMethod: mysqlEnum(['individual','digital_scale_stack','platform_scale']).default('individual').notNull(),
	palletWeight: decimal({ precision: 6, scale: 3 }),
	crateTypeId: int().references(() => crateTypes.id),
	transportDurationHours: decimal({ precision: 4, scale: 1 }),
	season: varchar({ length: 20 }),
	plannedStandardDensity: int(),
	plannedStandardCrates: int(),
	plannedOddDensity: int(),
	plannedOddCrates: int(),
	plannedTotalBirds: int(),
	availableCrates: int(),
},
(table) => [
	index("idx_catch_sessions_flock_id").on(table.flockId),
	index("idx_catch_sessions_catch_date").on(table.catchDate),
	index("idx_catch_sessions_status").on(table.status),
]);

export const chartOfAccounts = mysqlTable("chart_of_accounts", {
	id: int().autoincrement().notNull(),
	accountNumber: varchar({ length: 50 }).notNull(),
	accountName: varchar({ length: 200 }).notNull(),
	accountType: mysqlEnum(['asset','liability','equity','revenue','expense']).notNull(),
	accountSubtype: varchar({ length: 100 }),
	parentAccountId: int(),
	isActive: tinyint().default(1).notNull(),
	description: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("chart_of_accounts_accountNumber_unique").on(table.accountNumber),
	index("idx_chart_of_accounts_type").on(table.accountType),
]);

export const crateTypes = mysqlTable("crate_types", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 100 }).notNull(),
	length: decimal({ precision: 6, scale: 2 }).notNull(),
	width: decimal({ precision: 6, scale: 2 }).notNull(),
	height: decimal({ precision: 6, scale: 2 }).notNull(),
	tareWeight: decimal({ precision: 6, scale: 3 }).notNull(),
	isActive: tinyint().default(1).notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("idx_crate_types_name").on(table.name),
]);

export const customerAddresses = mysqlTable("customer_addresses", {
	id: int().autoincrement().notNull(),
	customerId: int().notNull().references(() => customers.id),
	addressType: mysqlEnum(['billing','delivery','both']).default('both').notNull(),
	addressLine1: varchar({ length: 200 }).notNull(),
	addressLine2: varchar({ length: 200 }),
	city: varchar({ length: 100 }),
	province: varchar({ length: 100 }),
	postalCode: varchar({ length: 20 }),
	country: varchar({ length: 100 }).default('South Africa'),
	isDefault: tinyint().default(0),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_customer_addresses_customer_id").on(table.customerId),
]);

export const customers = mysqlTable("customers", {
	id: int().autoincrement().notNull(),
	customerNumber: varchar({ length: 50 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	contactPerson: varchar({ length: 200 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	whatsapp: varchar({ length: 50 }),
	segment: mysqlEnum(['wholesale','retail','contract']).default('retail').notNull(),
	creditLimit: int().default(0),
	paymentTerms: varchar({ length: 100 }).default('cash'),
	taxNumber: varchar({ length: 100 }),
	isActive: tinyint().default(1).notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("customers_customerNumber_unique").on(table.customerNumber),
]);

export const documents = mysqlTable("documents", {
	id: int().autoincrement().notNull(),
	title: varchar({ length: 500 }).notNull(),
	description: text(),
	category: mysqlEnum(['contract','certificate','lab_report','invoice','compliance','vaccination_record','biosecurity','financial_statement','other']).notNull(),
	fileKey: varchar({ length: 500 }).notNull(),
	fileUrl: varchar({ length: 1000 }).notNull(),
	fileName: varchar({ length: 500 }).notNull(),
	fileSize: int(),
	mimeType: varchar({ length: 100 }),
	tags: text(),
	relatedEntityType: varchar({ length: 50 }),
	relatedEntityId: int(),
	expiryDate: timestamp({ mode: 'string' }),
	status: mysqlEnum(['active','archived','expired']).default('active').notNull(),
	uploadedAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	uploadedBy: int().references(() => users.id),
},
(table) => [
	index("idx_documents_category").on(table.category),
	index("idx_documents_related_entity").on(table.relatedEntityType, table.relatedEntityId),
]);

export const feedBatches = mysqlTable("feed_batches", {
	id: int().autoincrement().notNull(),
	batchNumber: varchar({ length: 100 }).notNull(),
	formulationId: int().notNull().references(() => feedFormulations.id),
	productionDate: timestamp({ mode: 'string' }).notNull(),
	quantity: decimal({ precision: 10, scale: 2 }).notNull(),
	rawMaterialCost: int().notNull(),
	laborCost: int().default(0),
	overheadCost: int().default(0),
	totalCost: int().notNull(),
	costPerTon: int().notNull(),
	qualityStatus: mysqlEnum(['pending','in_progress','passed','failed']).default('pending').notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("feed_batches_batchNumber_unique").on(table.batchNumber),
	index("idx_feed_batches_production_date").on(table.productionDate),
	index("idx_feed_batches_formulation_id").on(table.formulationId),
]);

export const feedFormulations = mysqlTable("feed_formulations", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 200 }).notNull(),
	feedRange: mysqlEnum(['premium','value','econo']).notNull(),
	feedStage: mysqlEnum(['starter','grower','finisher']).notNull(),
	version: int().default(1).notNull(),
	description: text(),
	ingredients: text().notNull(),
	proteinPercentage: decimal({ precision: 5, scale: 2 }),
	energyContent: decimal({ precision: 10, scale: 2 }),
	crudeProtein: decimal({ precision: 5, scale: 2 }),
	crudeFiber: decimal({ precision: 5, scale: 2 }),
	calcium: decimal({ precision: 5, scale: 2 }),
	phosphorus: decimal({ precision: 5, scale: 2 }),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("idx_feed_formulations_range_stage").on(table.feedRange, table.feedStage),
]);

export const flockDailyRecords = mysqlTable("flock_daily_records", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	recordDate: timestamp({ mode: 'string' }).notNull(),
	dayNumber: int().notNull(),
	mortality: int().default(0).notNull(),
	feedConsumed: decimal({ precision: 10, scale: 2 }).default('0'),
	feedType: mysqlEnum(['starter','grower','finisher']),
	waterConsumed: decimal({ precision: 10, scale: 2 }),
	averageWeight: decimal({ precision: 10, scale: 3 }),
	weightSamples: text(),
	temperature: decimal({ precision: 5, scale: 2 }),
	humidity: decimal({ precision: 5, scale: 2 }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	recordedBy: int().references(() => users.id),
},
(table) => [
	index("idx_flock_daily_records_flock_id").on(table.flockId),
	index("idx_flock_daily_records_record_date").on(table.recordDate),
]);

export const flockStressPackSchedules = mysqlTable("flock_stress_pack_schedules", {
	id: int().autoincrement().notNull(),
	flockId: int("flock_id").notNull(),
	stressPackId: int("stress_pack_id").notNull(),
	startDay: int("start_day").notNull(),
	endDay: int("end_day").notNull(),
	dosageStrength: mysqlEnum("dosage_strength", ['single','double','triple']).default('single'),
	status: mysqlEnum(['scheduled','active','completed','cancelled']).default('scheduled'),
	quantityUsed: varchar("quantity_used", { length: 100 }),
	notes: text(),
	createdAt: timestamp("created_at", { mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const flockVaccinationSchedules = mysqlTable("flock_vaccination_schedules", {
	id: int().autoincrement().notNull(),
	flockId: int("flock_id").notNull(),
	vaccineId: int("vaccine_id").notNull(),
	scheduledDay: int("scheduled_day").notNull(),
	status: mysqlEnum(['scheduled','completed','missed','rescheduled']).default('scheduled'),
	actualDate: timestamp("actual_date", { mode: 'string' }),
	dosageUsed: varchar("dosage_used", { length: 100 }),
	notes: text(),
	administeredBy: int("administered_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const flocks = mysqlTable("flocks", {
	id: int().autoincrement().notNull(),
	flockNumber: varchar({ length: 50 }).notNull(),
	houseId: int().notNull().references(() => houses.id),
	placementDate: timestamp({ mode: 'string' }).notNull(),
	initialCount: int().notNull(),
	currentCount: int().notNull(),
	targetSlaughterWeight: decimal({ precision: 10, scale: 2 }).default('1.70'),
	growingPeriod: int().default(42),
	status: mysqlEnum(['planned','active','harvesting','completed','cancelled']).default('planned').notNull(),
	collectionDate: timestamp({ mode: 'string' }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
	weightUnit: mysqlEnum(['grams','kg']).default('kg').notNull(),
	starterFeedType: mysqlEnum(['premium','value','econo']),
	starterFromDay: int().default(0),
	starterToDay: int(),
	growerFeedType: mysqlEnum(['premium','value','econo']),
	growerFromDay: int(),
	growerToDay: int(),
	finisherFeedType: mysqlEnum(['premium','value','econo']),
	finisherFromDay: int(),
	finisherToDay: int(),
	destinationName: varchar({ length: 255 }),
	destinationAddress: text(),
	destinationGpsLat: varchar({ length: 50 }),
	destinationGpsLng: varchar({ length: 50 }),
	travelDurationHours: decimal({ precision: 5, scale: 2 }),
	feedWithdrawalHours: int(),
	statusChangedAt: timestamp({ mode: 'string' }),
	statusChangedBy: int().references(() => users.id),
	statusChangeReason: text(),
	isManualStatusChange: tinyint().default(0),
	targetDeliveredWeight: decimal({ precision: 10, scale: 3 }),
	targetCatchingWeight: decimal({ precision: 10, scale: 3 }),
},
(table) => [
	index("flocks_flockNumber_unique").on(table.flockNumber),
	index("idx_flocks_house_id").on(table.houseId),
	index("idx_flocks_status").on(table.status),
	index("idx_flocks_placement_date").on(table.placementDate),
]);

export const generalLedgerEntries = mysqlTable("general_ledger_entries", {
	id: int().autoincrement().notNull(),
	entryNumber: varchar({ length: 50 }).notNull(),
	entryDate: timestamp({ mode: 'string' }).notNull(),
	accountId: int().notNull().references(() => chartOfAccounts.id),
	debit: int().default(0).notNull(),
	credit: int().default(0).notNull(),
	description: varchar({ length: 500 }).notNull(),
	referenceType: varchar({ length: 50 }),
	referenceId: int(),
	isReconciled: tinyint().default(0),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("general_ledger_entries_entryNumber_unique").on(table.entryNumber),
	index("idx_general_ledger_entries_account_id").on(table.accountId),
	index("idx_general_ledger_entries_entry_date").on(table.entryDate),
]);

export const harvestRecords = mysqlTable("harvest_records", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	harvestDate: timestamp({ mode: 'string' }).notNull(),
	harvestStartTime: timestamp({ mode: 'string' }).notNull(),
	harvestDurationMinutes: int(),
	feedWithdrawalStartTime: timestamp({ mode: 'string' }),
	feedWithdrawalDurationHours: decimal({ precision: 5, scale: 2 }),
	destination: varchar({ length: 255 }),
	chickenCountLoaded: int().notNull(),
	totalLoadedWeightKg: decimal({ precision: 10, scale: 3 }).notNull(),
	averageLoadedWeightKg: decimal({ precision: 10, scale: 3 }),
	totalCrates: int(),
	oddCrateCount: int(),
	oddCrateWeightKg: decimal({ precision: 10, scale: 3 }),
	transportDepartTime: timestamp({ mode: 'string' }),
	transportArrivalTime: timestamp({ mode: 'string' }),
	travelDurationHours: decimal({ precision: 5, scale: 2 }),
	chickenCountDelivered: int(),
	totalDeliveredWeightKg: decimal({ precision: 10, scale: 3 }),
	averageDeliveredWeightKg: decimal({ precision: 10, scale: 3 }),
	transportMortalities: int().default(0),
	shrinkagePercentage: decimal({ precision: 5, scale: 2 }),
	pricePerKg: decimal({ precision: 10, scale: 2 }),
	totalRevenue: decimal({ precision: 12, scale: 2 }),
	paymentTerms: varchar({ length: 100 }),
	invoiceReference: varchar({ length: 100 }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	recordedBy: int().references(() => users.id),
},
(table) => [
	index("idx_harvest_records_flock_id").on(table.flockId),
	index("idx_harvest_records_harvest_date").on(table.harvestDate),
]);

export const healthProtocolTemplates = mysqlTable("health_protocol_templates", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	description: text(),
	vaccinationSchedules: json("vaccination_schedules"),
	stressPackSchedules: json("stress_pack_schedules"),
	isDefault: tinyint("is_default").default(0),
	isActive: tinyint("is_active").default(1),
	createdBy: int("created_by").references(() => users.id),
	createdAt: timestamp("created_at", { mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const healthRecords = mysqlTable("health_records", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	recordDate: timestamp({ mode: 'string' }).notNull(),
	recordType: mysqlEnum(['observation','treatment','veterinary_visit','medication','other']).notNull(),
	description: text().notNull(),
	affectedBirds: int(),
	treatment: text(),
	medication: varchar({ length: 200 }),
	dosage: varchar({ length: 100 }),
	veterinarianName: varchar({ length: 200 }),
	cost: int(),
	followUpRequired: tinyint().default(0),
	followUpDate: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	recordedBy: int().references(() => users.id),
},
(table) => [
	index("idx_health_records_flock_id").on(table.flockId),
	index("idx_health_records_record_date").on(table.recordDate),
]);

export const houses = mysqlTable("houses", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 100 }).notNull(),
	houseNumber: varchar({ length: 50 }),
	length: decimal({ precision: 10, scale: 2 }).notNull(),
	width: decimal({ precision: 10, scale: 2 }).notNull(),
	floorArea: decimal({ precision: 10, scale: 2 }).notNull(),
	capacity: int().notNull(),
	houseType: mysqlEnum(['open_sided','closed','semi_closed']).default('closed').notNull(),
	beddingType: varchar({ length: 50 }).default('pine_shavings'),
	beddingDepth: int().default(30),
	numberOfFeeders: int(),
	numberOfDrinkers: int(),
	heatingType: varchar({ length: 50 }),
	ventilationType: varchar({ length: 50 }),
	notes: text(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
	breed: mysqlEnum(['ross_308','cobb_500','arbor_acres']).default('ross_308').notNull(),
	farmName: varchar({ length: 100 }),
	physicalAddress: text(),
	gpsLatitude: decimal({ precision: 10, scale: 7 }),
	gpsLongitude: decimal({ precision: 10, scale: 7 }),
	province: varchar({ length: 50 }),
	district: varchar({ length: 50 }),
	mortalityRate: decimal("mortality_rate", { precision: 5, scale: 2 }).default('4.00').notNull(),
	targetSlaughterWeight: decimal("target_slaughter_weight", { precision: 5, scale: 2 }).default('1.90').notNull(),
	densityKgPerSqm: decimal("density_kg_per_sqm", { precision: 5, scale: 2 }),
},
(table) => [
	index("houses_name_unique").on(table.name),
]);

export const inventoryItems = mysqlTable("inventory_items", {
	id: int().autoincrement().notNull(),
	itemNumber: varchar({ length: 50 }).notNull(),
	primaryClass: varchar("primary_class", { length: 2 }),
	subType: varchar("sub_type", { length: 2 }),
	form: varchar({ length: 3 }),
	name: varchar({ length: 200 }).notNull(),
	longDescription: text("long_description"),
	itemStatus: mysqlEnum("item_status", ['active','inactive','discontinued','obsolete']).default('active').notNull(),
	itemType: mysqlEnum("item_type", ['stocked_item','non_stocked','service','raw_material','finished_good','consumable']).default('stocked_item').notNull(),
	barcode: varchar({ length: 100 }),
	manufacturerPartNumber: varchar("manufacturer_part_number", { length: 100 }),
	internalReference: varchar("internal_reference", { length: 100 }),
	supplierPartNumber: varchar("supplier_part_number", { length: 100 }),
	brand: varchar({ length: 100 }),
	model: varchar({ length: 100 }),
	category: mysqlEnum(['live_birds','feed','raw_materials','supplies','equipment']).notNull(),
	unit: varchar({ length: 50 }).notNull(),
	currentStock: decimal({ precision: 10, scale: 2 }).default('0').notNull(),
	reorderPoint: decimal({ precision: 10, scale: 2 }),
	unitCost: int(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("inventory_items_itemNumber_unique").on(table.itemNumber),
	index("idx_inventory_items_barcode").on(table.barcode),
	index("idx_inventory_items_status").on(table.itemStatus),
	index("idx_inventory_items_type").on(table.itemType),
	index("idx_inventory_items_brand").on(table.brand),
	index("idx_inventory_items_mpn").on(table.manufacturerPartNumber),
]);

export const inventoryLocations = mysqlTable("inventory_locations", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 200 }).notNull(),
	locationType: mysqlEnum(['house','warehouse','silo','cold_storage','other']).notNull(),
	description: text(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("inventory_locations_name_unique").on(table.name),
]);

export const inventoryStock = mysqlTable("inventory_stock", {
	id: int().autoincrement().notNull(),
	itemId: int().notNull().references(() => inventoryItems.id),
	locationId: int().notNull().references(() => inventoryLocations.id),
	quantity: decimal({ precision: 10, scale: 2 }).default('0').notNull(),
	lastUpdated: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	updatedBy: int().references(() => users.id),
},
(table) => [
	index("unique_item_location").on(table.itemId, table.locationId),
	index("idx_inventory_stock_item_location").on(table.itemId, table.locationId),
]);

export const inventoryTransactions = mysqlTable("inventory_transactions", {
	id: int().autoincrement().notNull(),
	itemId: int().notNull().references(() => inventoryItems.id),
	locationId: int().references(() => inventoryLocations.id),
	transactionType: mysqlEnum(['receipt','issue','transfer','adjustment']).notNull(),
	quantity: decimal({ precision: 10, scale: 2 }).notNull(),
	unitCost: int(),
	totalCost: int(),
	referenceType: varchar({ length: 50 }),
	referenceId: int(),
	notes: text(),
	transactionDate: timestamp({ mode: 'string' }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("idx_inventory_transactions_item_id").on(table.itemId),
	index("idx_inventory_transactions_date").on(table.transactionDate),
]);

export const invoiceItems = mysqlTable("invoice_items", {
	id: int().autoincrement().notNull(),
	invoiceId: int().notNull().references(() => invoices.id),
	description: varchar({ length: 500 }).notNull(),
	quantity: decimal({ precision: 10, scale: 2 }).notNull(),
	unit: varchar({ length: 50 }).notNull(),
	unitPrice: int().notNull(),
	subtotal: int().notNull(),
	taxRate: decimal({ precision: 5, scale: 2 }).default('15.00'),
	taxAmount: int().notNull(),
	totalAmount: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_invoice_items_invoice_id").on(table.invoiceId),
]);

export const invoices = mysqlTable("invoices", {
	id: int().autoincrement().notNull(),
	invoiceNumber: varchar({ length: 50 }).notNull(),
	customerId: int().notNull().references(() => customers.id),
	orderId: int().references(() => salesOrders.id),
	invoiceDate: timestamp({ mode: 'string' }).notNull(),
	dueDate: timestamp({ mode: 'string' }).notNull(),
	subtotal: int().notNull(),
	taxAmount: int().notNull(),
	totalAmount: int().notNull(),
	paidAmount: int().default(0).notNull(),
	balanceDue: int().notNull(),
	status: mysqlEnum(['draft','sent','paid','partial','overdue','cancelled']).default('draft').notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("invoices_invoiceNumber_unique").on(table.invoiceNumber),
	index("idx_invoices_customer_id").on(table.customerId),
	index("idx_invoices_invoice_date").on(table.invoiceDate),
	index("idx_invoices_status").on(table.status),
	index("idx_invoices_due_date").on(table.dueDate),
]);

export const itemTemplates = mysqlTable("item_templates", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 200 }).notNull(),
	category: varchar({ length: 100 }).notNull(),
	calculationType: mysqlEnum(['area_based','bird_count_based','worker_based','fixed','custom']).notNull(),
	formula: text(),
	bufferPercentage: decimal({ precision: 5, scale: 2 }).default('10.00'),
	unit: varchar({ length: 50 }).notNull(),
	conversionFactor: decimal({ precision: 10, scale: 4 }),
	orderTriggerDays: int().notNull(),
	deliveryLeadDays: int().default(0),
	defaultSupplierId: int().references(() => suppliers.id),
	estimatedUnitCost: int(),
	isActive: tinyint().default(1).notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
});

export const mortalityRecords = mysqlTable("mortality_records", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	recordDate: timestamp({ mode: 'string' }).notNull(),
	count: int().notNull(),
	cause: varchar({ length: 200 }),
	ageAtDeath: int(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	recordedBy: int().references(() => users.id),
},
(table) => [
	index("idx_mortality_records_flock_id").on(table.flockId),
	index("idx_mortality_records_record_date").on(table.recordDate),
]);

export const paymentAllocations = mysqlTable("payment_allocations", {
	id: int().autoincrement().notNull(),
	paymentId: int().notNull().references(() => payments.id),
	invoiceId: int().notNull().references(() => invoices.id),
	amount: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_payment_allocations_payment_id").on(table.paymentId),
	index("idx_payment_allocations_invoice_id").on(table.invoiceId),
]);

export const payments = mysqlTable("payments", {
	id: int().autoincrement().notNull(),
	paymentNumber: varchar({ length: 50 }).notNull(),
	customerId: int().notNull().references(() => customers.id),
	paymentDate: timestamp({ mode: 'string' }).notNull(),
	amount: int().notNull(),
	paymentMethod: varchar({ length: 100 }).notNull(),
	referenceNumber: varchar({ length: 200 }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	recordedBy: int().references(() => users.id),
},
(table) => [
	index("payments_paymentNumber_unique").on(table.paymentNumber),
	index("idx_payments_customer_id").on(table.customerId),
	index("idx_payments_payment_date").on(table.paymentDate),
]);

export const processors = mysqlTable("processors", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	contactPerson: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	physicalAddress: text(),
	gpsLatitude: decimal({ precision: 10, scale: 7 }),
	gpsLongitude: decimal({ precision: 10, scale: 7 }),
	paymentTerms: varchar({ length: 100 }),
	defaultPricePerKg: decimal({ precision: 10, scale: 2 }),
	averageTravelTimeHours: decimal({ precision: 5, scale: 2 }),
	operatingDays: varchar({ length: 100 }),
	operatingHours: varchar({ length: 100 }),
	notes: text(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("name").on(table.name),
]);

export const procurementOrderItems = mysqlTable("procurement_order_items", {
	id: int().autoincrement().notNull(),
	orderId: int().notNull().references(() => procurementOrders.id),
	scheduleId: int().references(() => procurementSchedules.id),
	description: varchar({ length: 500 }).notNull(),
	quantity: decimal({ precision: 10, scale: 2 }).notNull(),
	unit: varchar({ length: 50 }).notNull(),
	unitPrice: int(),
	totalAmount: int(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_procurement_order_items_order_id").on(table.orderId),
]);

export const procurementOrders = mysqlTable("procurement_orders", {
	id: int().autoincrement().notNull(),
	orderNumber: varchar({ length: 50 }).notNull(),
	supplierId: int().notNull().references(() => suppliers.id),
	orderDate: timestamp({ mode: 'string' }).notNull(),
	expectedDeliveryDate: timestamp({ mode: 'string' }),
	actualDeliveryDate: timestamp({ mode: 'string' }),
	totalAmount: int(),
	status: mysqlEnum(['draft','sent','confirmed','delivered','cancelled']).default('draft').notNull(),
	sentVia: mysqlEnum(['email','whatsapp','phone','manual']),
	sentAt: timestamp({ mode: 'string' }),
	confirmedAt: timestamp({ mode: 'string' }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("procurement_orders_orderNumber_unique").on(table.orderNumber),
	index("idx_procurement_orders_supplier_id").on(table.supplierId),
	index("idx_procurement_orders_order_date").on(table.orderDate),
]);

export const procurementSchedules = mysqlTable("procurement_schedules", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	itemTemplateId: int().notNull().references(() => itemTemplates.id),
	supplierId: int().notNull().references(() => suppliers.id),
	calculatedQuantity: decimal({ precision: 10, scale: 2 }).notNull(),
	adjustedQuantity: decimal({ precision: 10, scale: 2 }),
	finalQuantity: decimal({ precision: 10, scale: 2 }).notNull(),
	unit: varchar({ length: 50 }).notNull(),
	estimatedCost: int(),
	scheduledOrderDate: timestamp({ mode: 'string' }).notNull(),
	scheduledDeliveryDate: timestamp({ mode: 'string' }),
	actualOrderDate: timestamp({ mode: 'string' }),
	actualDeliveryDate: timestamp({ mode: 'string' }),
	status: mysqlEnum(['pending','ordered','confirmed','delivered','cancelled']).default('pending').notNull(),
	orderReference: varchar({ length: 200 }),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("idx_procurement_schedules_flock_id").on(table.flockId),
	index("idx_procurement_schedules_status").on(table.status),
	index("idx_procurement_schedules_order_date").on(table.scheduledOrderDate),
]);

export const qualityControlRecords = mysqlTable("quality_control_records", {
	id: int().autoincrement().notNull(),
	batchId: int().notNull().references(() => feedBatches.id),
	testDate: timestamp({ mode: 'string' }).notNull(),
	testType: varchar({ length: 100 }).notNull(),
	parameter: varchar({ length: 100 }).notNull(),
	measuredValue: decimal({ precision: 10, scale: 3 }),
	targetValue: decimal({ precision: 10, scale: 3 }),
	tolerance: decimal({ precision: 10, scale: 3 }),
	result: mysqlEnum(['pass','fail','pending']).notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	testedBy: int().references(() => users.id),
},
(table) => [
	index("idx_quality_control_records_batch_id").on(table.batchId),
]);

export const rawMaterialTransactions = mysqlTable("raw_material_transactions", {
	id: int().autoincrement().notNull(),
	rawMaterialId: int().notNull().references(() => rawMaterials.id),
	transactionType: mysqlEnum(['purchase','usage','adjustment','return']).notNull(),
	quantity: decimal({ precision: 10, scale: 2 }).notNull(),
	unitCost: int(),
	totalCost: int(),
	referenceType: varchar({ length: 50 }),
	referenceId: int(),
	notes: text(),
	transactionDate: timestamp({ mode: 'string' }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("idx_raw_material_transactions_material_id").on(table.rawMaterialId),
	index("idx_raw_material_transactions_date").on(table.transactionDate),
]);

export const rawMaterials = mysqlTable("raw_materials", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 200 }).notNull(),
	category: varchar({ length: 100 }),
	unit: varchar({ length: 50 }).notNull(),
	currentStock: decimal({ precision: 10, scale: 2 }).default('0').notNull(),
	reorderPoint: decimal({ precision: 10, scale: 2 }),
	reorderQuantity: decimal({ precision: 10, scale: 2 }),
	unitCost: int(),
	supplierId: int(),
	isActive: tinyint().default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("raw_materials_name_unique").on(table.name),
]);

export const reminderTemplates = mysqlTable("reminder_templates", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 200 }).notNull(),
	description: text(),
	reminderType: mysqlEnum(['vaccination','feed_transition','house_preparation','environmental_check','routine_task','milestone','biosecurity','performance_alert','house_light_timing']).notNull(),
	priority: mysqlEnum(['urgent','high','medium','low']).default('medium').notNull(),
	dayOffset: int("day_offset").notNull(),
	isActive: tinyint("is_active").default(1).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	isBundle: tinyint("is_bundle").default(0).notNull(),
	bundleConfig: json("bundle_config"),
});

export const reminders = mysqlTable("reminders", {
	id: int().autoincrement().notNull(),
	flockId: int().references(() => flocks.id),
	houseId: int().references(() => houses.id),
	reminderType: mysqlEnum(['vaccination','feed_transition','house_preparation','environmental_check','routine_task','milestone','biosecurity','performance_alert','house_light_timing']).notNull(),
	title: varchar({ length: 200 }).notNull(),
	description: text(),
	dueDate: timestamp({ mode: 'string' }).notNull(),
	priority: mysqlEnum(['urgent','high','medium','low']).default('medium').notNull(),
	status: mysqlEnum(['pending','completed','dismissed']).default('pending').notNull(),
	completedAt: timestamp({ mode: 'string' }),
	completedBy: int().references(() => users.id),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	actionNotes: text(),
	templateId: int().references(() => reminderTemplates.id),
},
(table) => [
	index("idx_reminders_flock_id").on(table.flockId),
	index("idx_reminders_house_id").on(table.houseId),
	index("idx_reminders_due_date").on(table.dueDate),
	index("idx_reminders_status").on(table.status),
]);

export const salesOrderItems = mysqlTable("sales_order_items", {
	id: int().autoincrement().notNull(),
	orderId: int().notNull().references(() => salesOrders.id),
	itemType: mysqlEnum(['live_birds','feed','other']).notNull(),
	description: varchar({ length: 500 }).notNull(),
	flockId: int().references(() => flocks.id),
	feedBatchId: int().references(() => feedBatches.id),
	quantity: decimal({ precision: 10, scale: 2 }).notNull(),
	unit: varchar({ length: 50 }).notNull(),
	unitPrice: int().notNull(),
	subtotal: int().notNull(),
	taxRate: decimal({ precision: 5, scale: 2 }).default('15.00'),
	taxAmount: int().notNull(),
	totalAmount: int().notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_sales_order_items_order_id").on(table.orderId),
]);

export const salesOrders = mysqlTable("sales_orders", {
	id: int().autoincrement().notNull(),
	orderNumber: varchar({ length: 50 }).notNull(),
	customerId: int().notNull().references(() => customers.id),
	orderDate: timestamp({ mode: 'string' }).notNull(),
	deliveryDate: timestamp({ mode: 'string' }),
	deliveryAddressId: int().references(() => customerAddresses.id),
	status: mysqlEnum(['draft','confirmed','processing','delivered','cancelled']).default('draft').notNull(),
	subtotal: int().notNull(),
	taxAmount: int().notNull(),
	totalAmount: int().notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	createdBy: int().references(() => users.id),
},
(table) => [
	index("sales_orders_orderNumber_unique").on(table.orderNumber),
	index("idx_sales_orders_customer_id").on(table.customerId),
	index("idx_sales_orders_order_date").on(table.orderDate),
	index("idx_sales_orders_status").on(table.status),
]);

export const stressPacks = mysqlTable("stress_packs", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	brand: varchar({ length: 255 }).notNull(),
	manufacturer: varchar({ length: 255 }),
	dosageStrength: mysqlEnum("dosage_strength", ['single','double','triple']).default('single'),
	dosagePerLiter: varchar("dosage_per_liter", { length: 100 }),
	recommendedDurationDays: int("recommended_duration_days"),
	instructions: text(),
	costPerKg: varchar("cost_per_kg", { length: 20 }),
	isActive: tinyint("is_active").default(1),
	createdAt: timestamp("created_at", { mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	activeIngredients: text("active_ingredients"),
});

export const suppliers = mysqlTable("suppliers", {
	id: int().autoincrement().notNull(),
	supplierNumber: varchar({ length: 50 }).notNull(),
	name: varchar({ length: 200 }).notNull(),
	contactPerson: varchar({ length: 200 }),
	email: varchar({ length: 320 }),
	phone: varchar({ length: 50 }),
	whatsapp: varchar({ length: 50 }),
	preferredContactMethod: mysqlEnum(['email','whatsapp','phone','both']).default('email'),
	category: varchar({ length: 100 }),
	paymentTerms: varchar({ length: 100 }).default('cash'),
	taxNumber: varchar({ length: 100 }),
	bankName: varchar({ length: 200 }),
	bankAccountNumber: varchar({ length: 100 }),
	isActive: tinyint().default(1).notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
},
(table) => [
	index("suppliers_supplierNumber_unique").on(table.supplierNumber),
]);

export const userActivityLogs = mysqlTable("user_activity_logs", {
	id: int().autoincrement().notNull(),
	userId: int().notNull().references(() => users.id),
	action: varchar({ length: 100 }).notNull(),
	entityType: varchar({ length: 50 }),
	entityId: int(),
	details: text(),
	ipAddress: varchar({ length: 45 }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
},
(table) => [
	index("idx_user_activity_logs_user_id").on(table.userId),
	index("idx_user_activity_logs_created_at").on(table.createdAt),
]);

export const users = mysqlTable("users", {
	id: int().autoincrement().notNull(),
	openId: varchar({ length: 64 }),
	name: text(),
	email: varchar({ length: 320 }),
	loginMethod: varchar({ length: 64 }).default('email').notNull(),
	role: mysqlEnum(['admin','farm_manager','accountant','sales_staff','production_worker']).default('production_worker').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastSignedIn: timestamp({ mode: 'string' }),
	isActive: tinyint().default(1).notNull(),
	username: varchar({ length: 50 }),
	passwordHash: varchar({ length: 255 }),
	mustChangePassword: tinyint().default(1).notNull(),
	createdBy: int(),
},
(table) => [
	index("users_openId_unique").on(table.openId),
	index("users_username_unique").on(table.username),
	index("users_email_unique").on(table.email),
]);

export const vaccinationSchedules = mysqlTable("vaccination_schedules", {
	id: int().autoincrement().notNull(),
	flockId: int().notNull().references(() => flocks.id),
	vaccineName: varchar({ length: 200 }).notNull(),
	scheduledDate: timestamp({ mode: 'string' }).notNull(),
	scheduledDayNumber: int().notNull(),
	administeredDate: timestamp({ mode: 'string' }),
	dosage: varchar({ length: 100 }),
	administrationMethod: varchar({ length: 100 }),
	batchNumber: varchar({ length: 100 }),
	status: mysqlEnum(['scheduled','completed','skipped','overdue']).default('scheduled').notNull(),
	notes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	administeredBy: int().references(() => users.id),
},
(table) => [
	index("idx_vaccination_schedules_flock_id").on(table.flockId),
	index("idx_vaccination_schedules_scheduled_date").on(table.scheduledDate),
]);

export const vaccines = mysqlTable("vaccines", {
	id: int().autoincrement().notNull(),
	name: varchar({ length: 255 }).notNull(),
	brand: varchar({ length: 255 }).notNull(),
	manufacturer: varchar({ length: 255 }),
	diseaseType: mysqlEnum("disease_type", ['newcastle_disease','infectious_bronchitis','gumboro','mareks','coccidiosis','fowl_pox','other']).notNull(),
	applicationMethod: mysqlEnum("application_method", ['drinking_water','spray','eye_drop','injection','wing_web']).notNull(),
	dosagePerBird: varchar("dosage_per_bird", { length: 100 }),
	boosterIntervalDays: int("booster_interval_days"),
	instructions: text(),
	withdrawalPeriodDays: int("withdrawal_period_days").default(0),
	isActive: tinyint("is_active").default(1),
	createdAt: timestamp("created_at", { mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	vaccineType: mysqlEnum("vaccine_type", ['live','inactivated','recombinant','vector']).notNull(),
	storageTemperature: varchar("storage_temperature", { length: 100 }),
	shelfLifeDays: int("shelf_life_days"),
});
